### ISSUE TITLE
Server details -> connect doesn't actually connect you

### ISSUE THREAD

**Issue by Niklas-Eckhoff** [punyhumangames/BladeSymphony#90] opened 2018-11-03 05:55 UTC
**Requirements:**
Be in the _Server Browser game menu_.

**Steps:**
(1) LM click on a server
(2) LM click on the _Details UI element_
(3) LM click on the _Connect UI element_

**Results:**
You are back in the _Server Browser game menu_ and have not connected to the server.

You can now of course connect to the server but this isn't the purpose of the UI element.

**Comment by sampavlovic** [comment] 2018-11-06 03:19
Duplicate of #52

**Closed as completed** 2018-11-06 03:20 UTC
